import { ICard } from "./interface";

const BulkData: ICard[] = [
    {
        ru_header: '',
        eng_header: 'Abro Landing',
        ru_desc: '',
        eng_desc: 'Fast, clean and adaptive landing with challenging css work under hood. Hosted on Tilda, powered by Vanilla JS',
        ul_eng: ['Figma layout reauires gradient border and shadow, which became a CSS skill test', 'Pixelperfect', 'Adaptive'],
        tags: ['VanillaJS', 'Adaptive', 'Pixelperfect'],
        repo_url: 'https://codepen.io/RAV1OL33/pen/abEEpaW',
        demo_url: 'http://abro57.ru/',
    },
    {
        ru_header: '',
        eng_header: 'Pushka-39',
        ru_desc: '',
        eng_desc: 'Vanilla JS site, hosted on Tilda. That demanded to create some really unique workarounds to fullfil customer requirements',
        ul_eng: ['Backend on Google Sheets instead of full-fledged admin pannel', 'Handcrafted handler for CSS  "position: sticky" events', 'HTTPS setup and certification on nic.ru', 'Pixelperfect', 'Adaptive'],
        tags: ['VanillaJS', 'GoogleSheets', 'Adaptive', 'Pixelperfect'],
        repo_url: '',
        demo_url: 'https://pushka39.ru/',
    },
    {
        ru_header: '',
        eng_header: 'Pushka-39 (Angular 12)',
        ru_desc: '',
        eng_desc: 'Modern version of the "Pushka-39" site powered by newest angular. ',
        ul_eng: ['Noticeably reduced load speed', 'From Figma layout to the result in a few days', 'Build-in adaptive thanks to flexbox'],
        tags: ['Angular', 'GoogleSheets', 'Adaptive', ],
        repo_url: '',
        demo_url: 'https://rav1ol33.github.io/Pushka-39/',
    },
    {
        ru_header: '',
        eng_header: 'Search Assistant',
        ru_desc: '',
        eng_desc: 'Simple helper app, used to regain angular skills, and yet proven useful',
        ul_eng: [],
        tags: ['Angular', 'Bootstrap'],
        repo_url: 'https://github.com/RAV1OL33/Search-Try-prod',
        demo_url: 'https://rav1ol33.github.io/Search-Try-prod/',
    },
    {
        ru_header: '',
        eng_header: 'Stocks income graph builder',
        ru_desc: '',
        eng_desc: 'Another helper app. Canvas graph builder powered by Vanilla JS with Google Sheet as backend',
        ul_eng: ['A couple of little thins to increase perfomance'],
        tags: ['VanillaJS', 'GoogleSheets'],
        repo_url: 'https://codepen.io/RAV1OL33/pen/MWmWBzW',
        demo_url: 'https://codepen.io/RAV1OL33/pen/MWmWBzW',
    },
    {
        ru_header: '',
        eng_header: 'TXT to XLS/XLSX parser',
        ru_desc: '',
        eng_desc: 'C# parser with create a table from a .txt file',
        ul_eng: ['Experience in work without any documentation', 'First created c# App'],
        tags: ['c#'],
        repo_url: '',
        demo_url: '',
    },
    {
        ru_header: '',
        eng_header: 'Python parsers with Selenium',
        ru_desc: '',
        eng_desc: 'Various parsers for various tasks. Starting from content grabbing and ending with work automation',
        ul_eng: ['Vk/inst parsing', 'Domains grabbing', 'Various tasks automation (like script which move personal files from dropbox to Ya.Diskq)'],
        tags: ['Python', 'Selenium'],
        repo_url: '',
        demo_url: '',
    },
    {
        ru_header: '',
        eng_header: 'Experience_Pond',
        ru_desc: '',
        eng_desc: 'This one',
        ul_eng: ['It`s Cool'],
        tags: ['Angular','Adaptive'],
        repo_url: 'https://github.com/RAV1OL33/rewiev-hub',
        demo_url: '',
    },
    // {
    //     ru_header: '',
    //     eng_header: '',
    //     ru_desc: '',
    //     eng_desc: '',
    //     ul_eng: [],
    //     tags: [],
    //     repo_url: '',
    //     demo_url: '',
    // },
]
export {BulkData}