import { ICard } from "./interface";

const BulkData: ICard[] = [
    {
        ru_header: '',
        eng_header: 'Abro Landing',
        ru_desc: '',
        eng_desc: 'Fast, clean and adaptive landing page on Vanilla JS. Uses custom made CSS effects',
        ul_eng: ['Custom made gradient border and shadow', 'Pixelperfect', 'Adaptive'],
        tags: ['VanillaJS', 'Adaptive', 'Pixelperfect'],
        repo_url: 'https://codepen.io/RAV1OL33/pen/abEEpaW',
        demo_url: 'http://abro57.ru/',
    },
    {
        ru_header: '',
        eng_header: 'Pushka-39',
        ru_desc: '',
        eng_desc: 'Vanilla JS site, hosted on Tilda. Made a proprietary JS library to handle customer\'s requirements ',
        ul_eng: ['Used API to store and modify data, turning Google Sheets into a user friendly backend solution', 'Created a CSS event handler from scratch', 'HTTPS setup',],
        tags: ['VanillaJS', 'GoogleSheets', 'Adaptive', 'Pixelperfect'],
        repo_url: '',
        demo_url: 'https://pushka39.ru/',
    },
    {
        ru_header: '',
        eng_header: 'Pushka-39 (Angular 12)',
        ru_desc: '',
        eng_desc: 'Modernized version of the "Pushka-39" site powered by newest Angular. ',
        ul_eng: ['Noticeably reduced load speed', 'From Figma layout to the finished product in a few days', 'Build-in adaptive layout thanks to flexbox'],
        tags: ['Angular', 'GoogleSheets', 'Adaptive', ],
        repo_url: '',
        demo_url: 'https://rav1ol33.github.io/Pushka-39/',
    },
    {
        ru_header: '',
        eng_header: 'Search Assistant',
        ru_desc: '',
        eng_desc: 'Simple helper app, used to brush up on Angular skills. Later proven useful for stock trading optimization',
        ul_eng: [],
        tags: ['Angular', 'Bootstrap'],
        repo_url: 'https://github.com/RAV1OL33/Search-Try-prod',
        demo_url: 'https://rav1ol33.github.io/Search-Try-prod/',
    },
    {
        ru_header: '',
        eng_header: 'Stocks income graph builder',
        ru_desc: '',
        eng_desc: 'Another helper app. Canvas graph builder powered by Vanilla JS with Google Sheets backend',
        ul_eng: ['Custom made prediction algorithm for stock profitability', 'Perfomance optimization for large sample sizes of market data'],
        tags: ['VanillaJS', 'GoogleSheets'],
        repo_url: 'https://codepen.io/RAV1OL33/pen/MWmWBzW',
        demo_url: 'https://codepen.io/RAV1OL33/pen/MWmWBzW',
    },
    {
        ru_header: '',
        eng_header: 'TXT to XLS/XLSX parser',
        ru_desc: '',
        eng_desc: 'C# parser importing .txt files into a database',
        ul_eng: ['Reverse engineering undocumented API', ],
        tags: ['CSharp'],
        repo_url: '',
        demo_url: '',
    },
    {
        ru_header: '',
        eng_header: 'Python + Selenium',
        ru_desc: '',
        eng_desc: '',
        ul_eng: ['Social network API parsing (Vk etc.)', 'Web-crawlers', 'Genering a dataset of avilable names for any domain', 'Automating OS/Server tasks, ranging from RSS aggregation to remote file backup'],
        tags: ['Python', 'Selenium'],
        repo_url: '',
        demo_url: '',
    },
    {
        ru_header: '',
        eng_header: 'Experience_Pond',
        ru_desc: '',
        eng_desc: 'This one',
        ul_eng: ['It`s Cool'],
        tags: ['Angular','Adaptive'],
        repo_url: 'https://github.com/RAV1OL33/rewiev-hub/',
        demo_url: 'https://rav1ol33.github.io/rewiev-hub/',
    },
    // {
    //     ru_header: '',
    //     eng_header: '',
    //     ru_desc: '',
    //     eng_desc: '',
    //     ul_eng: [],
    //     tags: [],
    //     repo_url: '',
    //     demo_url: '',
    // },
]
export {BulkData}